```{r}
library(haven)
library(tidyverse)
library(ggplot2)


library(ggiraphExtra)
```



```{r}
# Daten einlesen
# in chunk fehler ausblenden
data <- read_csv("Data/main_data.csv")

```

```{r}
# Exemplarisch fuer "EAST Interconnection"

data_1 <- data %>% 
  select(date, intercn, CO2MASS, coal_price, gasprice, meant, load, nonFossil) %>% 
  mutate(CR = coal_price/gasprice, CO2MASS=CO2MASS/1000000) %>% 
  filter(intercn=="EAST")
```



```{r}
#Linear Regression - Step 1

# EVTL "FELM" statt lm fixed effects etc.


fit <- lm(CO2MASS ~ CR, data=data_1) # make a model
fit_resid <- resid(fit)

new.data <- data.frame(CR = seq(from = min(data_1$CR),
                                 to = max(data_1$CR), length.out = 2557))


predict.linear <- predict(fit, newdata = new.data)

p1 <- predict(fit, newdata = data_1)
plot(CO2MASS~CR, data_1)
lines(data_1$CR, p1, col="red")

#ggplot(data_1, aes(x=CR, y=CO2MASS)) + geom_point()+stat_smooth(se=F, method='lm', formula=y~x)

plot(data_1$CR, fit_resid,
  ylab="Residuals", xlab="Cost Ratio", 
  main="",
  abline(0,0))

preds <- data.frame(new.data,linear=predict.linear)
preds <- reshape2::melt(preds,
                        id.vars = 1)

ggplot(data = preds)+
  geom_line(aes(x = CR, y = value, color = variable ))+
  geom_point(data = data_1, aes(x = CR, y = CO2MASS))+
  theme_bw()

plot(fit)

#ggPredict(fit)

################# evtl function fuer regression plot? eh alle gleich #####################

library(lfe)


fit_test = felm(CO2MASS ~ CR, data=data_1)


regression.result(fit, fit_test)

```

```{r}
#how to function // exkurs
regression.result= function(...){
  library(stargazer)
    stargazer(..., 
            type = "text", 
            style = "aer",  
            digits = 3,
            df = FALSE,
            report = "vct*",
            star.cutoffs = c(0.05, 0.01, 0.001),
            #model.names = FALSE,
            #object.names = TRUE,
            #model.numbers = FALSE, 
            omit.stat=c("f", "ser")
    )
} 


regression.result(fit)
```




```{r}
#Quardratic Regression - Step 2
CR.squared <- data_1$CR^2

fit2 <- lm(CO2MASS ~ CR + CR.squared, data_1)
fit2_resid <- resid(fit2)
p2 <- predict(fit2, data_1)
#domain <- seq(min(data_1$CR), max(data_1$CR))    # define a vector of x values to feed into model

CR.cubed <- data_1$CR^3
fit3 <- lm(CO2MASS ~ CR + CR.squared + CR.cubed, data_1)
p3 <- predict(fit3, data_1)

plot(CO2MASS ~ CR, data_1)    # plot points
lines(smooth.spline(data_1$CR, p1), col = "blue")
lines(smooth.spline(data_1$CR, p2), col = "red")
lines(smooth.spline(data_1$CR, p3), col = "green")# add regression line, using `predict` to generate y-values

plot(data_1$CR, fit2_resid,
  ylab="Residuals", xlab="Cost Ratio", 
  main="",
  abline(0,0))

library(stargazer)
summary(fit)
summary(fit2)
summary(fit3)
#reg.summary
#stargazer(fit2)

anova(fit,fit2,fit3)
```



```{r}
#Add control variables - Section 4
model_formula <- CO2MASS ~ CR * load * meant * nonfossil
fit4 <- lm(CO2MASS ~ CR + load + meant + nonFossil, data_1)
fit4_resid <- resid(fit4)

#ggPredict(fit4)

summary(fit4)

plot(fit4)
coefficients(fit4)

p4 <- predict(fit4, data_1)

plot(CO2MASS ~ CR, data_1)    # plot points
lines(data_1$CR, p4, col = "blue")    # add regression line, using `predict` to generate y-values


plot(data_1$CR, fit4_resid,
  ylab="Residuals", xlab="Cost Ratio", 
  main="",
  abline(0,0))


library(regtools)


effectplot(fit4, show.ci = TRUE)

################## IDEE
new.data2 <- data.frame(CR = seq(from = min(data_1$CR), to = max(data_1$CR),length.out = 2557),
                        load = seq(from = min(data_1$load), to = max(data_1$load),length.out = 2557),
                        meant = seq(from = min(data_1$meant), to = max(data_1$meant),length.out = 2557),
                        nonFossil = seq(from = min(data_1$nonFossil), to = max(data_1$nonFossil),length.out = 2557))





predict.linear2 <- predict(fit4, newdata = new.data2)

preds2 <- data.frame(new.data2,linear=predict.linear2)
preds2 <- reshape2::melt(preds2,
                        id.vars = 1)

ggplot(data = preds2)+
  geom_line(aes(x = CR, y = value, color = variable ))+
  geom_point(data = data_1, aes(x = CR, y = CO2MASS))+
  theme_bw()

```










```{r}
################# CUBIC SPLINE DRAFT ######################
#modell mit allen variablen???????????
library(splines)
model <- bs(data_1$CR, df = 3, knots=6)
fm1 <- lm(CO2MASS~bs(gasprice), data=data_1)

fit <-predict(fm1, interval = "confidence")

## predict CO2 bei 5.75 fuer % 

5.395963

#create new dataframe with fitted values and confidence band
fit <- as.data.frame(fit)
CO2_pred <- data.frame(CO2MASS = data_1$CO2MASS,
                       gasprice = data_1$gasprice,
                       predicted_values = fit$fit,
                       predicted_lwr = fit$lwr,
                       predicted_upr = fit$upr)

#Transform into percentage changes regards to predicted co2-emission at base-gasprice
CO2_pred <- CO2_pred %>% 
  mutate(predicted_values_perc = predicted_values/5.395963-1,
         predicted_lwr_perc = predicted_lwr/5.357381-1,
         predicted_upr_perc = predicted_upr/5.434546-1)

#plot
ggplot(CO2_pred, aes(x=gasprice, y=CO2MASS) ) +
  geom_line(aes(y = predicted_values_perc), colour = "red") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(2, 12)) +
  geom_vline(xintercept = 5.75, linetype = "dashed") +
  geom_ribbon(data=CO2_pred, aes(ymin=predicted_lwr_perc, ymax=predicted_upr_perc), alpha=0.3)



summary(fm1)

```



```{r}
library(caret)
library(mgcv)
# Build the model
model <- gam(CO2MASS ~ s(CR)+meant+load, data = data_1)
# Make predictions
predictions <- model %>% predict(data_1)

fit5 <- predict.gam(model)


# Model performance
data.frame(
  RMSE = RMSE(predictions, data_1$CO2MASS),
  R2 = R2(predictions, data_1$CO2MASS)
)

plot(CO2MASS ~ gasprice, data=data_1)

plot(CO2MASS ~ gasprice, data=data_1)
lines(fit5, data_1$gasprice, col = "blue")

ggplot(data_1, aes(gasprice, CO2MASS) ) +
  #geom_point() +
  stat_smooth(method = gam, formula = y ~ s(x))+
  scale_x_reverse()


#grid.arrange(plot1, plot2, ncol=2)
```




```{r}

library("mgcv")
model <- CO2MASS ~ gasprice + load + meant + nonFossil + so2price + netNSflow
#model <- CO2MASS ~ s(gasprice, bs = 'cr', k=3) + s(meant, bs= 're') + s(load, bs= 're')

fit <- gam(model, data = data_1, family = "gaussian", discrete = TRUE, nthreads = 2)


#summary(fit)

#invisible(gam.check(fit))

#plot.gam(fit, page = 1)

co2_pred <- data.frame(CO2MASS = data_1$CO2MASS,
                       gasprice = data_1$gasprice,
                       fitted = fit$fitted.values)

plot(fitted~gasprice, data=co2_pred)


CO2_pred <- data.frame(CO2MASS = data_1$CO2MASS,
                       gasprice = data_1$gasprice,
                       predicted_values = predict.gam(fit, newdata = data_1))

CO2_pred <- CO2_pred %>% 
  mutate(temp = predicted_values/5.395963-1)

#ggplot(CO2_pred, aes(x = gasprice)) +
#  geom_point(aes(y = CO2MASS), size = 1, alpha = 0.5) + stat_smooth(aes(y = predicted_values), colour = "red")

#ggplot(CO2_pred, aes(x = gasprice)) +
#  geom_point(aes(y = CO2MASS), size = 1, alpha = 0.5) + stat_smooth(aes(y = predicted_values), colour = "red")



ggplot(CO2_pred, aes(x=gasprice, y=CO2MASS) ) +
  #geom_point() 
  
  geom_smooth(aes(y = temp), colour = "red", method="gam", formula = y ~ splines::bs(x, 5)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(limits=c(2, 12)) +
  geom_vline(xintercept = 5.75, linetype = "dashed")
 # scale_x_reverse()

summary(fit)



ggplot(co2_pred, aes(x=gasprice, y=fitted)) +
  geom_line()

```




```{r}
newd <- data.frame(gasprice = 6, meant = 45, load=7500000)
oo <- predict.bam(fit, newd, se.fit = TRUE)

new <- data.frame(test2, data_1$gasprice)
test2 <- as.data.frame(test)
new
test <- predict.bam(fit ~ data_1$gasprice)
str(test2)
plot(x=data_1.gasprice, y=test , data=new)
length(data_1$gasprice)

test

plot(x=data_1.gasprice, y=test , data=new)
new

plot(fit)
```

```{r}
library(ggplot2)
theme_set(theme_bw())
library(dplyr)
library(mgcv)
library(tidymv)



model_p <- predict.bam(model)
model_p


predict.bam(model) %>% 
  ggplot(aes(gasprice2, CO2MASS))+
  geom_smooth_ci()
```






